---
- import_playbook: gather_policy_info.yml

- hosts: all
  become: yes
  tasks:
    - name: Creating OpenSCAP cron.d configuration
      cron:
        name: "Generate OpenSCAP profile for profile {{ hostvars['localhost']['policy']['id'] }}" 
        cron_file: /etc/cron.d/foreman_openscap_client
        job: /usr/bin/foreman_scap_client {{ hostvars['localhost']['policy']['id'] }}
        user: root
        minute: "{{ minute }}"
        hour: "{{ hour }}"
        day: "{{ day }}" 
        weekday: "{{ weekday }}"
        month: "{{ month }}"
        state: present
